### ISSUE TITLE
Can external dependencies do url replacement in css

### ISSUE THREAD

**Issue by keshin** [lasso-js/lasso#139]
Hi
Here are my case, I have a css resolved from bower, which have an import for some external resource like below:
```css
@import url("https://fonts.googleapis.com/css?family=Roboto:300,400,500,700");
/*!
 * bootswatch v3.3.6
 * Homepage: http://bootswatch.com
 * Copyright 2012-2015 Thomas Park
 * Licensed under MIT
 * Based on Bootstrap
*/
/*!
 * Bootstrap v3.3.6 (http://getbootstrap.com)
 * Copyright 2011-2015 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 */
/*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */
html {
  font-family: sans-serif;
  -ms-text-size-adjust: 100%;
  -webkit-text-size-adjust: 100%;
}
```

What I want is manage the fonts resource in first line. I can add it in `browser.json` with `external:false`, while I'm not sure if lasso will be the url replacement in the css file above?
