### ISSUE TITLE
Add support for UTF8 encoding inline images in CSS files

### ISSUE THREAD

**Issue by patrick-steele-idem** [lasso-js/lasso#141]
Example usage:

```css
.foo {
    background-image: url(./circle.svg?utf8);
}
```
