### ISSUE TITLE
Docs: Add documentation for base64 encoding of images

### ISSUE THREAD

**Issue by patrick-steele-idem** [lasso-js/lasso#69]
You just need to append a special ?base64 querystring to the image page in your CSS.

__Input CSS:__

```css
.foo {
   background-image: url(./foo.png?base64);
}
```

__Output CSS:__

```css
.foo {
   background-image: url(data:...);
}
```
